# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CelularAutomataMarkovChain
                                 A QGIS plugin
 This plugin used to predict land cover change using Celular Automata Markov Chain
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-08
        copyright            : (C) 2024 by SvyorPreneur
        email                : tedyselan@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CelularAutomataMarkovChain class from file CelularAutomataMarkovChain.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ca_markov_chain import CelularAutomataMarkovChain
    return CelularAutomataMarkovChain(iface)
